remote_theme: chrisrhymes/bulma-clean-theme
title: SuicideOS
baseurl: ""
permalink: pretty
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: false
      hide_hero: true
      theme_color: "#000000"
      comments: false
