name: 'Documentation'

on:
  pull_request:
    branches:
    - main

jobs:
  terraform-docs:
    name: 'Generate Terraform Documentation'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: website

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check
