name: Pull Request Actions

on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    name: Run Pre-Commit
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Run pre-commit
        uses: pre-commit/action@v2.0.0

  terraform-docs:
    name: Generate Terraform Documentation
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Run terraform-docs
        uses: terraform-docs/gh-actions@v0.4.0
        with:
          working-dir: website
          output-file: README.md
          output-method: inject
          git-push: "true"
