name: 'Pull Request Actions'

on:
  pull_request:
    branches:
    - main

jobs:
  terraform-docs:
    name: 'Generate Terraform Documentation'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    
    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v0.4.0
      with:
        working-dir: website
        output-file: README.md
        output-method: inject
        git-push: "true"
